### ISSUE TITLE
Entity Person

### ISSUE THREAD

**Issue by saniochky** [Paliy2/Project-alias#13]
### Description

Entity Person has to be created and have the following properties:

- [x] `name : String` -- to record the name of the Person; `Composite Key`. (No whitespaces, less than 20 characters)
- [x] `surname : String` -- to record the name of the Person; `Composite Key`. (No whitespaces, less than 40 characters)
- [x] `phoneNumber: String` -- to record the phone number of the Person. (No whitespaces, in format +38 (099) 222 3344, required)
- [x] `email: String` -- to record the email of the Person; `Composite Key`. (No whitespaces)

It is also necessary to create `Person Centre` to search and review the existing persons and `Person Master` to create new and edit existing persons.

### Expected outcome

Entity Person can be created with the necessary fields.

**Comment by 01es** [comment]
In our learning domain, the concepts of `User` and `Person` were separated for a reason  – they represent 2 very different concerns. `User` is a low-level system concept that is a part of the IS security subsystem. `Person` is a domain concept representing people involved in the organisation's operations and processes. Some persons could be users, which is why we had property `Person.user: User`, and some persons would never have a corresponding user.

This is why properties `login` and `password` do not belong to entity `Person`. In fact, you do not need to worry about the `User` concept, authentication and authorisation as this is already covered by the core functionality of TG for you.

Also, when designing model for your domain concepts, always think of the business key – what represents instances in the population of some concept uniquely from the business point of view (i.e. not a surrogate ID).

**Comment by Khrystia-Sliusarchuk** [comment]
> In our learning domain, the concepts of `User` and `Person` were separated for a reason – they represent 2 very different concerns. `User` is a low-level system concept that is a part of the IS security subsystem. `Person` is a domain concept representing people involved in the organisation's operations and processes. Some persons could be users, which is why we had property `Person.user: User`, and some persons would never have a corresponding user.
> 
> This is why properties `login` and `password` do not belong to entity `Person`. In fact, you do not need to worry about the `User` concept, authentication and authorisation as this is already covered by the core functionality of TG for you.
> 
> Also, when designing model for your domain concepts, always think of the business key – what represents instances in the population of some concept uniquely from the business point of view (i.e. not a surrogate ID).

We removed `login` and `password` as you have mentioned in the comment. Also, we chose `name`, `surname` and `email` to be composite key members.

**Comment by saniochky** [comment]
Task is done
